services:
    app.admin.user_inline:
        class: App\User\Admin\UserInlineAdmin
        arguments: [~, App\User\Entity\User, ~]
        tags:
            - {name: sonata.admin, manager_type: orm}

    app.admin.user_role:
        class: App\User\Admin\UserRoleAdmin
        arguments: [~, App\User\Entity\UserRole, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'User', label: 'User Role'}
        public: true
