<?php

namespace BlackStork\Core\Repository;

/**
 * SeoDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoDataRepository extends \Doctrine\ORM\EntityRepository
{
}
