<?php

namespace Brisum\Stork\Bundle\CoreBundle\Repository;

/**
 * SeoDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoDataEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
