<?php

namespace Brisum\Stork\Bundle\CoreBundle\Repository;

/**
 * SeoTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
