stork_admin:
    resource: "@StorkCoreBundle/Controller/Admin/"
    type:     annotation
    prefix:   /%strok_admin_area%

stork_page:
    resource: "@StorkCoreBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /
