black_stork_admin:
    resource: "@BlackStorkCoreBundle/Controller/Admin/"
    type:     annotation
    prefix:   /%strok_admin_area%

black_stork_page:
    resource: "@BlackStorkCoreBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /
