services:
    stork.sonata_admin.employee:
        class: BlackStork\Core\SonataAdmin\EmployeeAdmin
        arguments: [~, BlackStork\Core\Entity\Employee, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Employee', label: 'Employees'}

    stork.sonata_admin.page:
        class: BlackStork\Core\SonataAdmin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Page", label: "Page" }
        arguments:
            - ~
            - BlackStork\Core\Entity\Page
            - ~
        calls:
            - [ inject, ['@service_container']]
        public: true

    stork.sonata_admin.page_seo_data:
        class: BlackStork\Core\SonataAdmin\PageSeoDataAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Page", label: "SeoData" }
        arguments:
            - ~
            - BlackStork\Core\Entity\PageSeoData
            - ~
        calls:
            - [ inject, ['@service_container']]
        public: true

    stork.sonata_admin.seo_template:
        class: BlackStork\Core\SonataAdmin\SeoTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Seo", label: "Seo Template" }
        arguments:
            - ~
            - BlackStork\Core\Entity\SeoTemplate
            - ~
        calls:
            - [setContainer, ['@service_container']]
        public: true
